name: "Build and publish life garden"
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

permissions:
  contents: write

concurrency:
  group: pages-branch
  cancel-in-progress: false

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Deploy
        run: bash tools/deploy.sh
